name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # The Steam Runtime platform (sniper) uses Python 3.9
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get install shellcheck
          python3 -m pip install --upgrade pip
          pip install ruff
          pip install ijson
          pip install trio
          pip install "steam[client]"
      - name: Lint with Shellcheck
        run: |
          shellcheck winetricks
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: Validate gamefix modules
        run: |
          python3 .github/scripts/check_gamefixes.py
          python3 .github/scripts/check_verbs.py
      # We need a known parent package in the unit tests, so we need to change to the parent dir
      # As "umu-protonfixes" is not a valid package name, we create a symbolic link to "protonfixes"
      - name: Fix package resolution
        run: |
          ln -s umu-protonfixes ../protonfixes
      - name: Validate gamefix imports
        run: |
          python3 .github/scripts/check_imports.py
      - name: Test with unittest
        run: |
          cd ..
          python3 -m protonfixes.protonfixes_test
